apiVersion: v1
kind: Pod
metadata:
  name: reload-pod
spec:
  containers:
  - name: watcher
    image: busybox
    command: ["sh", "-c", "while true; do cat /config/message; sleep 5; done"]
    volumeMounts:
    - name: vol
      mountPath: /config
  volumes:
  - name: vol
    configMap:
      name: live-config